backend:
  name: git-gateway
  branch: master

# media_folder: 'assets/img'
# public_folder: '/img'

media_library:
  name: cloudinary
  config:
    cloud_name: dttbfql17
    api_key: 211247722988129

# media_library:
#   name: uploadcare
#   config:
#     publicKey: 93c2788ba01bd03e49b4 # replace with your Public API key or use for testing env only

collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: ID,
          name: id,

          # Default widget name
          widget: ncw-id,

          # <Optional> If `true`, add timestamp, i.e post-1588747959991-dnfuHvOhP
          # This can be used to sort collection by creation time
          timestamp: false,

          # <Optional> Hide the widget from UI
          # Beware: We literally add `display: none` to the DOM node wrapping the input. It will break if netlifyCMS's editor pane structure changes.
          hidden: false,
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Short Descripcion',
          name: 'short_description',
          widget: 'string',
        }
      - { label: 'Long Description', name: 'long_description', widget: 'text' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          multiple: true,
          min: 1,
          max: 3,
          options: ['Social Media Design', 'Web Design', 'Art Direction'],
        }
      - {
          label: 'Thumbnail',
          name: 'thumbnail',
          widget: 'image',
          allow_multiple: false,
        }
      - label: 'Project Images'
        name: 'images'
        widget: 'object'
        fields:
          - {
              label: 'RRSS Images',
              name: 'rrss',
              widget: 'image',
              media_library: { config: { multiple: true } },
              required: false,
            }
          - {
              label: 'WEB Images',
              name: 'web',
              widget: 'image',
              media_library: { config: { multiple: true } },
              required: false,
            }

          # - {
          #     label: 'RRSS Images',
          #     name: 'rrss',
          #     widget: 'list',
          #     summary: '{{fields.image}}',
          #     field: { label: 'Image', name: 'image', widget: 'image' },
          #     required: false,
          #   }
          # - {
          #     label: 'Web Images',
          #     name: 'web',
          #     widget: 'list',
          #     summary: '{{fields.image}}',
          #     field: { label: 'Image', name: 'image', widget: 'image' },
          #     required: false,
          #   }
